local auth = require("src.server.auth")
local sha2 = require("src.vendor.sha2")

local function hex(bin) return sha2.bin_to_hex(bin) end

describe("PBKDF2-HMAC-SHA256", function()

    local VECTORS = {
        { pass = "password", salt = "salt", iter = 1, dklen = 32,
          hex = "120fb6cffcf8b32c43e7225256c4f837a86548c92ccc35480805987cb70be17b" },
        { pass = "password", salt = "salt", iter = 2, dklen = 32,
          hex = "ae4d0c95af6b46d32d0adff928f06dd02a303f8ef3c251dfd6e2d85a95474c43" },
        { pass = "password", salt = "salt", iter = 4096, dklen = 32,
          hex = "c5e478d59288c841aa530db6845c4c8d962893a001ce4e11a4963873aa98134a" },
        { pass = "passwordPASSWORDpassword",
          salt = "saltSALTsaltSALTsaltSALTsaltSALTsalt", iter = 4096, dklen = 40,
          hex = "348c89dbcbd32b2f32d814b8116e84cf2b17347ebc1800181c4e2a1fb8dd53e1"
             .. "c635518c7dac47e9" },
    }

    it("matches the published vectors on the active backend", function()
        for i, v in ipairs(VECTORS) do
            local got = auth.pbkdf2_hmac_sha256(v.pass, v.salt, v.iter, v.dklen)
            assert.are.equal(v.hex, hex(got), "vector " .. i .. " mismatch")
        end
    end)

    it("matches the published vectors on the pure-Lua implementation", function()
        for i, v in ipairs(VECTORS) do
            local got = auth.pbkdf2_pure(v.pass, v.salt, v.iter, v.dklen)
            assert.are.equal(v.hex, hex(got), "vector " .. i .. " mismatch")
        end
    end)

    it("agrees with the pure implementation across output lengths", function()
        for _, dklen in ipairs({ 1, 16, 20, 32, 33, 45, 64 }) do
            local salt = "\0\xFFsalty-salt"
            local native = auth.pbkdf2_hmac_sha256("hunter2", salt, 37, dklen)
            local pure   = auth.pbkdf2_pure("hunter2", salt, 37, dklen)
            assert.are.equal(#native, dklen)
            assert.are.equal(hex(pure), hex(native), "dklen " .. dklen)
        end
    end)

    it("agrees on binary passwords and salts", function()
        local pass = "p\0ss\xC3\xA9\xFF"
        local salt = "\0\1\2\3\xFE\xFF"
        assert.are.equal(hex(auth.pbkdf2_pure(pass, salt, 64, 32)),
                         hex(auth.pbkdf2_hmac_sha256(pass, salt, 64, 32)))
    end)

    it("reports a backend", function()
        local b = auth.kdf_backend()
        assert.is_true(b == "openssl" or b == "lua")
    end)
end)

describe("password hashing round-trip", function()
    it("verifies a hash it just produced", function()
        local stored = auth.hash_password("correct horse", { iterations = 2000 })
        local parsed, err = auth.parse_hash(stored)
        assert.is_nil(err)
        assert.are.equal(2000, parsed.iterations)

        local a = auth.static_authenticator{
            username = "u", password_hash = stored, ban_duration = 0,
        }
        assert.is_true(a:verify("u", "correct horse", "1.2.3.4"))
    end)

    it("rejects a wrong password", function()
        local stored = auth.hash_password("correct horse", { iterations = 2000 })
        local a = auth.static_authenticator{
            username = "u", password_hash = stored, ban_duration = 0,
        }
        local ok, err = a:verify("u", "wrong horse", "1.2.3.5")
        assert.is_false(ok)
        assert.is_string(err)
    end)

    it("accepts a hash generated by the other backend", function()
        local salt = "\x01\x02\x03\x04\x05\x06\x07\x08"
        local raw  = auth.pbkdf2_pure("shared secret", salt, 3000, 32)
        local stored = string.format("pbkdf2-sha256$%d$%s$%s",
            3000, sha2.bin_to_hex(salt), sha2.bin_to_hex(raw))

        local a = auth.static_authenticator{
            username = "u", password_hash = stored, ban_duration = 0,
        }
        assert.is_true(a:verify("u", "shared secret", "1.2.3.6"))
    end)
end)

describe("verify cost estimate", function()
    it("scales with the iteration count", function()
        local one = auth.estimate_verify_seconds(10000)
        local ten = auth.estimate_verify_seconds(100000)
        assert.is_true(one > 0)
        assert.is_true(ten > one)
    end)

    it("puts the native backend far under a handshake deadline", function()
        if auth.kdf_backend() ~= "openssl" then
            pending("no native KDF backend on this host")
            return
        end
        assert.is_true(auth.estimate_verify_seconds(600000) < 1.0)
    end)
end)
