local Buffer = require("src.core.buffer")

describe("Buffer", function()
    local buf

    before_each(function()
        buf = Buffer.new()
    end)

    it("starts empty", function()
        assert.are.equal(0, buf:len())
        assert.are.equal("", buf:bytes())
    end)

    it("accumulates writes in order", function()
        buf:write("hello")
        buf:write(" ")
        buf:write("world")
        assert.are.equal("hello world", buf:bytes())
        assert.are.equal(11, buf:len())
    end)

    it("handles empty-string writes", function()
        buf:write("")
        buf:write("x")
        buf:write("")
        assert.are.equal("x", buf:bytes())
        assert.are.equal(1, buf:len())
    end)

    it("reset() clears contents and size", function()
        buf:write("abc")
        buf:write("def")
        buf:reset()
        assert.are.equal(0, buf:len())
        assert.are.equal("", buf:bytes())
    end)

    it("can be reused after reset()", function()
        buf:write("first")
        buf:reset()
        buf:write("second")
        assert.are.equal("second", buf:bytes())
        assert.are.equal(6, buf:len())
    end)

    it("preserves binary data including embedded NULs", function()
        buf:write("a\0b")
        buf:write("\0\0")
        assert.are.equal("a\0b\0\0", buf:bytes())
        assert.are.equal(5, buf:len())
    end)
end)
