local Parser = require("src.repl.sql.parser")

-- Parse a single statement and return its AST node (asserting success).
local function one(src)
    local stmts, err = Parser.parse(src)
    assert(stmts, err and err.message)
    assert.equals(1, #stmts, "expected exactly one statement")
    return stmts[1]
end

describe("sql parser", function()
    describe("CREATE TOPIC", function()
        it("defaults to a single partition", function()
            local n = one("CREATE TOPIC orders;")
            assert.same({ type = "create_topic", name = "orders", partitions = 1 }, n)
        end)

        it("reads an explicit partition count", function()
            local n = one("create topic orders partitions 4;")
            assert.equals(4, n.partitions)
        end)

        it("errors when the name is missing", function()
            local stmts, err = Parser.parse("CREATE TOPIC;")
            assert.is_nil(stmts)
            assert.matches("topic name", err.message)
        end)
    end)

    describe("LIST / SHOW", function()
        it("parses LIST TOPICS", function()
            assert.equals("list_topics", one("LIST TOPICS;").type)
        end)
        it("accepts SHOW TOPICS as an alias", function()
            assert.equals("list_topics", one("SHOW TOPICS;").type)
        end)
        it("parses SHOW GROUP", function()
            assert.equals("show_group", one("SHOW GROUP;").type)
        end)
    end)

    describe("PRODUCE", function()
        it("parses topic, key and value", function()
            local n = one("PRODUCE INTO orders KEY 'k1' VALUE 'payload';")
            assert.same({ type = "produce", topic = "orders", key = "k1", value = "payload" }, n)
        end)

        it("defaults the key to empty when omitted", function()
            local n = one("PRODUCE INTO orders VALUE 'payload';")
            assert.equals("", n.key)
        end)

        it("requires a VALUE", function()
            local stmts, err = Parser.parse("PRODUCE INTO orders KEY 'k';")
            assert.is_nil(stmts)
            assert.matches("VALUE", err.message)
        end)
    end)

    describe("FETCH", function()
        it("defaults group nil and limit 100", function()
            local n = one("FETCH FROM orders;")
            assert.equals("orders", n.topic)
            assert.is_nil(n.group)
            assert.equals(100, n.limit)
        end)

        it("reads group and limit", function()
            local n = one("FETCH FROM orders GROUP billing LIMIT 50;")
            assert.equals("billing", n.group)
            assert.equals(50, n.limit)
        end)

        it("requires FROM", function()
            local stmts, err = Parser.parse("FETCH orders;")
            assert.is_nil(stmts)
            assert.matches("FROM", err.message)
        end)
    end)

    describe("SUBSCRIBE", function()
        it("defaults timeout to 5s", function()
            local n = one("SUBSCRIBE TO orders;")
            assert.equals("subscribe", n.type)
            assert.equals(5, n.timeout)
        end)
        it("reads group, timeout and limit", function()
            local n = one("SUBSCRIBE orders GROUP g TIMEOUT 10 LIMIT 3;")
            assert.equals("g", n.group)
            assert.equals(10, n.timeout)
            assert.equals(3, n.limit)
        end)
    end)

    describe("COMMIT", function()
        it("parses topic, partition and offset", function()
            local n = one("COMMIT orders PARTITION 0 OFFSET 42;")
            assert.same({ type = "commit", topic = "orders", partition = 0, offset = 42 }, n)
        end)
    end)

    describe("consumer groups", function()
        it("CREATE GROUP maps to join_group with a topic list", function()
            local n = one("CREATE GROUP billing SUBSCRIBE orders, payments;")
            assert.equals("join_group", n.type)
            assert.equals("billing", n.group)
            assert.same({ "orders", "payments" }, n.topics)
        end)
        it("JOIN GROUP parses too", function()
            local n = one("JOIN GROUP g SUBSCRIBE t;")
            assert.equals("join_group", n.type)
            assert.same({ "t" }, n.topics)
        end)
        it("LEAVE GROUP and HEARTBEAT are keyword-only", function()
            assert.equals("leave_group", one("LEAVE GROUP;").type)
            assert.equals("heartbeat", one("HEARTBEAT;").type)
        end)
    end)

    describe("connection & meta", function()
        it("CONNECT reads a bare host and clauses in any order", function()
            local n = one("CONNECT 'localhost' PORT 9092 USER 'admin' PASSWORD 'pw';")
            assert.equals("localhost", n.host)
            assert.equals(9092, n.port)
            assert.equals("admin", n.user)
            assert.equals("pw", n.password)
        end)
        it("DISCONNECT, HELP, EXIT and QUIT parse", function()
            assert.equals("disconnect", one("DISCONNECT;").type)
            assert.equals("help", one("HELP;").type)
            assert.equals("fetch", one("HELP fetch;").topic)
            assert.equals("quit", one("EXIT;").type)
            assert.equals("quit", one("QUIT;").type)
        end)
    end)

    describe("multiple statements & errors", function()
        it("parses several semicolon-separated statements", function()
            local stmts = assert(Parser.parse("LIST TOPICS; HEARTBEAT; QUIT;"))
            assert.equals(3, #stmts)
            assert.equals("list_topics", stmts[1].type)
            assert.equals("heartbeat", stmts[2].type)
            assert.equals("quit", stmts[3].type)
        end)

        it("tolerates stray semicolons", function()
            local stmts = assert(Parser.parse(";; LIST TOPICS;;"))
            assert.equals(1, #stmts)
        end)

        it("requires a terminating semicolon", function()
            local stmts, err = Parser.parse("LIST TOPICS")
            assert.is_nil(stmts)
            assert.matches("';'", err.message)
        end)

        it("rejects an unknown command", function()
            local stmts, err = Parser.parse("DESTROY EVERYTHING;")
            assert.is_nil(stmts)
            assert.is_string(err.message)
        end)
    end)
end)
